### ISSUE TITLE
Error: object 'pseudobulk' is not exported by 'namespace:basejump'

### ISSUE THREAD

**Issue by dpryan79** [hbc/bcbioSingleCell#91]
Xref: https://github.com/bioconda/bioconda-recipes/pull/20415

It looks like the bioconda recipe for this is using the versions specified in Description, but nonetheless the following error is happening during installation:

    Error: object 'pseudobulk' is not exported by 'namespace:basejump'

I'm guessing that either something needs to be changed in basejump or that a more recent version of it is required.

**Comment by mjsteinbaugh** [comment]
Thanks @dpryan79, I'll double check the release

**Comment by mjsteinbaugh** [comment]
OK this should be fixed with the v0.4.9 release, see pull request: https://github.com/hbc/bcbioSingleCell/pull/92/files

I'll work on updating the recipe from the autobump
